# Whether this GitHub repo is engineering related
engineering_project: true
# Name of the repository/project in English
english_name: CC Chooser
# All technologies used
technologies: HTML, CSS, JS, Bulma, Vue, Jest
# Whether this repository should be featured on the CC Open Source site
featured: true
