# https://prettier.io/docs/en/options.html#print-width
printWidth: 79

# https://prettier.io/docs/en/options.html#bracket-line
bracketSameLine: true

# https://prettier.io/docs/en/options.html#single-attribute-per-line
singleAttributePerLine: true
